-- ========================================
-- Migration: Add Ghost Contractors Table
-- Purpose: Store web-scraped contractor profiles for external fallback
-- Date: 2026-01-18
-- ========================================

-- ========================================
-- 1. Create ghost_contractors table
-- Stores contractors found via web search (Tavily API + GPT-4o parsing)
-- These are "unclaimed" profiles that contractors can claim later
-- ========================================
CREATE TABLE IF NOT EXISTS ghost_contractors (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Basic Info
  company_name TEXT NOT NULL,
  phone TEXT,
  email TEXT,
  trade TEXT, -- e.g., "electrician", "plumber", "hvac"
  location_zip TEXT,

  -- Web Search Metadata
  rating TEXT DEFAULT '0.0',
  review_count INTEGER DEFAULT 0,
  source_url TEXT, -- URL where contractor was found (Yelp, Angie's List, etc.)
  is_unclaimed BOOLEAN DEFAULT true, -- True until contractor claims profile
  is_ai_generated BOOLEAN DEFAULT false, -- True if fallback AI-generated

  -- Timestamps
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

  -- Claimed Info (when contractor claims profile)
  claimed_at TIMESTAMP WITH TIME ZONE,
  claimed_by_user_id UUID REFERENCES user_profiles(id) ON DELETE SET NULL
);

-- Indexes for ghost_contractors
CREATE INDEX IF NOT EXISTS idx_ghost_contractors_phone ON ghost_contractors(phone);
CREATE INDEX IF NOT EXISTS idx_ghost_contractors_trade ON ghost_contractors(trade);
CREATE INDEX IF NOT EXISTS idx_ghost_contractors_zip ON ghost_contractors(location_zip);
CREATE INDEX IF NOT EXISTS idx_ghost_contractors_unclaimed ON ghost_contractors(is_unclaimed) WHERE is_unclaimed = true;
CREATE INDEX IF NOT EXISTS idx_ghost_contractors_created_at ON ghost_contractors(created_at DESC);

-- ========================================
-- 2. Add GPS coordinates to job_postings
-- Needed for SentinelAgent GPS verification
-- ========================================
ALTER TABLE job_postings
  ADD COLUMN IF NOT EXISTS site_latitude DECIMAL(10, 8),
  ADD COLUMN IF NOT EXISTS site_longitude DECIMAL(11, 8);

-- Create index for GPS lookups
CREATE INDEX IF NOT EXISTS idx_job_postings_gps ON job_postings(site_latitude, site_longitude);

-- ========================================
-- 3. Comments
-- ========================================
COMMENT ON TABLE ghost_contractors IS 'External contractor profiles found via web search (Tavily API). Contractors can claim these profiles to convert to full accounts.';
COMMENT ON COLUMN ghost_contractors.is_unclaimed IS 'True until a registered contractor claims this profile';
COMMENT ON COLUMN ghost_contractors.is_ai_generated IS 'True if generated by AI fallback (when Tavily API unavailable)';
COMMENT ON COLUMN ghost_contractors.source_url IS 'URL where contractor info was scraped from (Yelp, HomeAdvisor, etc.)';

COMMENT ON COLUMN job_postings.site_latitude IS 'Project site GPS latitude (for Sentinel location verification)';
COMMENT ON COLUMN job_postings.site_longitude IS 'Project site GPS longitude (for Sentinel location verification)';
